const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Indulge in fluffy perfection with our irresistible Buttermilk Pancakes. Delight your taste buds with a classic breakfast favorite, expertly crafted to melt in your mouth. `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Get ready for a taste sensation with Diner Double. Double the juicy patties, double the cheese, and double the satisfaction. Indulge in a mouthwatering burger experience that will leave you craving for seconds.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Unleash your taste buds with the monstrous indulgence of our Godzilla Milkshake. Brace yourself for a towering blend of creamy goodness, erupting with flavor and topped with delicious decadence. Conquer your dessert cravings with this colossal shake experience.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Discover the pure taste of freshness with Country Delight. Savor the goodness of farm-fresh milk, delivered directly to your doorstep. Experience dairy products that are as authentic and delightful as nature intended.`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Prepare for an egg-citing adventure with Egg Attack. Experience the ultimate breakfast delight as our perfectly cooked eggs unleash a burst of flavor. Get ready to conquer your morning cravings with this egg-centric sensation.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Embark on a dreamy delight with Oreo Dream. Immerse yourself in a world of chocolatey bliss as the classic Oreo cookie takes center stage. Indulge in a heavenly fusion of creamy perfection and delightful crunch. Let Oreo Dream transport you to cookie paradise.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Indulge in savory bliss with Bacon Overflow. Dive into a crispy, smoky sensation that will leave your taste buds craving more. Experience the irresistible allure of perfectly cooked bacon, overflowing with flavor.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Experience the timeless taste of nostalgia with American Classic. Indulge in a culinary journey that pays homage to the iconic flavors of American cuisine. Savor the perfect blend of tradition and innovation, crafted to satisfy your cravings with every bite.`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `Find your ultimate Quarantine Buddy. Discover a companion that keeps you entertained, connected, and informed during these challenging times. Embrace the perfect partner to share laughter, explore new hobbies, and make the most of your quarantine experience.`,
  },
];
export default menu;
